# Ubuntu VM - thay upstream.host bằng IP Host-only của Windows.
node.id=RELAY-01
node.role=RELAY
bind.host=0.0.0.0
self.port=18002
upstream.host=192.168.56.1
upstream.port=18888
victim.id=VICTIM-01
victim.host=127.0.0.1
victim.port=18001
